### ISSUE TITLE
Odd GMT offsets

### ISSUE THREAD

**Issue by rlbyrd** [mcmastermind/jClocksGMT-WP#1]
This isn't so much an issue as a clarification request.  I figured this out, but others might not.  For oddball timezone offsets (e.g., Mumbai is +5:30) simply use the decimal representation in the clock tags:  +5.5.  This isn't in the documentation anywhere; might be good to add it.

Cheers.

**Comment by mcmastermind** [comment]
Thanks! i will add it to the documentation
